// sim_main.cpp — Verilator simulation wrapper for custom 8-bit RISC CPU
//
// Build:
//   verilator --cc --exe --build -Isrc src/*.v sim/sim_main.cpp
//   ./obj_dir/Vcpu_core
//
// Exposes: PC, IR, FSM state, registers, flags per clock cycle.
// Supports single-step mode via command-line flag.
//
// Compile (after Verilator generates Vcpu_core.h):
//   g++ -O2 -I obj_dir -I $VERILATOR_ROOT/include \
//       obj_dir/Vcpu_core__ALL.a                   \
//       $VERILATOR_ROOT/include/verilated.cpp       \
//       sim/sim_main.cpp -o sim_cpu

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <verilated.h>
#include "Vcpu_core_debug.h"      // Generated by Verilator

// ── Constants ────────────────────────────────────────────────
static const uint64_t MAX_CYCLES = 100000;  // safety stop

// ── FSM state names ──────────────────────────────────────────
static const char* STATE_NAMES[] = {"FETCH", "DECODE", "EXECUTE", "WRITEBACK"};

// ── Register dump ────────────────────────────────────────────
static void dump_registers(Vcpu_core_debug* dut) {
    uint64_t packed = dut->dbg_regfile;
    printf("  Regs: ");
    for (int i = 0; i < 8; i++) {
        uint8_t r = (packed >> (8 * i)) & 0xFF;
        printf("R%d=%3u ", i, r);
    }
    printf("\n");
}

// ── Flag decode ──────────────────────────────────────────────
static void dump_flags(Vcpu_core_debug* dut) {
    uint8_t f = dut->dbg_flags;
    printf("  Flags: Z=%u C=%u N=%u V=%u\n",
           (f >> 0) & 1,   // zero
           (f >> 1) & 1,   // carry
           (f >> 2) & 1,   // negative
           (f >> 3) & 1);  // overflow
}

// ── Clock tick ───────────────────────────────────────────────
static void tick(Vcpu_core_debug* dut, VerilatedContext* ctx) {
    dut->clk = 0;
    dut->eval();
    ctx->timeInc(5);    // 5 ns half-period → 10 ns clock

    dut->clk = 1;
    dut->eval();
    ctx->timeInc(5);
}

// ── Main ─────────────────────────────────────────────────────
int main(int argc, char** argv) {
    VerilatedContext* ctx = new VerilatedContext;
    ctx->commandArgs(argc, argv);

    Vcpu_core_debug* dut = new Vcpu_core_debug(ctx);

    // Parse arguments
    bool single_step  = false;
    bool verbose      = false;
    bool wb_only      = true;   // default: print only at WRITEBACK
    uint64_t max_cyc  = MAX_CYCLES;

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--step")    == 0) single_step = true;
        if (strcmp(argv[i], "--verbose") == 0) { verbose = true; wb_only = false; }
        if (strcmp(argv[i], "--cycles")  == 0 && i+1 < argc)
            max_cyc = (uint64_t)atoll(argv[++i]);
    }

    // Enable debug bus
    dut->dbg_en   = 1;
    dut->dbg_step = 0;

    // ── Reset ──────────────────────────────────────────────
    dut->reset = 1;
    tick(dut, ctx);
    tick(dut, ctx);
    dut->reset = 0;

    printf("╔══════════════════════════════════════════╗\n");
    printf("║  CPU Simulation — Verilator Wrapper v0.3 ║\n");
    printf("╚══════════════════════════════════════════╝\n\n");

    uint64_t cycle = 0;
    bool     at_wb = false;

    while (!ctx->gotFinish() && cycle < max_cyc) {
        at_wb = (dut->dbg_state == 3);  // WRITEBACK = 2'b11

        tick(dut, ctx);
        cycle++;

        bool print_now = verbose || (wb_only && at_wb);

        if (print_now) {
            const char* sname = STATE_NAMES[dut->dbg_state & 0x3];
            printf("Cycle %5llu  t=%6llu ns  [%-9s]  PC=%04X  IR=%04X\n",
                   (unsigned long long)cycle,
                   (unsigned long long)ctx->time(),
                   sname,
                   (unsigned)dut->dbg_pc,
                   (unsigned)dut->dbg_ir);

            if (at_wb) {
                dump_registers(dut);
                dump_flags(dut);

                // Single-step pause
                if (single_step) {
                    printf("  [STEP] Press ENTER to continue...\n");
                    getchar();
                }
            }
        }

        // Detect NOP at PC≥11 as program end (adjust for your program)
        if (at_wb && dut->dbg_ir == 0x0000 && dut->dbg_pc >= 11) {
            printf("\n=== Program reached NOP sentinel — simulation complete ===\n");
            break;
        }
    }

    if (cycle >= max_cyc)
        printf("\n=== Cycle limit %llu reached ===\n", (unsigned long long)max_cyc);

    printf("\nFinal state after %llu cycles:\n", (unsigned long long)cycle);
    dump_registers(dut);
    dump_flags(dut);
    printf("PC = %04X\n", (unsigned)dut->dbg_pc);

    dut->final();
    delete dut;
    delete ctx;
    return 0;
}